name: SAST Scan

on:
  push:
    branches:
      - feature/shopsmart-72
  pull_request:
    branches:
      - feature/shopsmart-72

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}