name: DAST Scan

on:
  push:
    branches:
      - feature/shopsmart-72
  pull_request:
    branches:
      - feature/shopsmart-72

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8080'